//==============================================================================
//
// The code is generated by Intel Compiler for SystemC, version 1.6.3
// see more information at https://github.com/intel/systemc-compiler
//
//==============================================================================

//==============================================================================
//
// Module: half_adder ()
//
module half_adder // "tb.dut_inst"
(
    input logic clk,
    input logic rstn,
    input logic a,
    input logic b,
    output logic sum,
    output logic carry
);

//------------------------------------------------------------------------------
// Clocked THREAD: prc_half_adder (half_adder.h:24:5) 

// Thread-local variables
logic sum_next;
logic carry_next;

// Next-state combinational logic
always_comb begin : prc_half_adder_comb     // half_adder.h:24:5
    prc_half_adder_func;
end
function void prc_half_adder_func;
    logic s_nand;
    logic s_or;
    carry_next = carry;
    sum_next = sum;
    s_nand = !(a & b);
    s_or = a | b;
    sum_next = s_nand & s_or;
    carry_next = a & b;
endfunction

// Synchronous register update
always_ff @(posedge clk or negedge rstn) 
begin : prc_half_adder_ff
    if ( ~rstn ) begin
    end
    else begin
        sum <= sum_next;
        carry <= carry_next;
    end
end

endmodule


